In [9]:
import numpy as np
import matplotlib.pyplot as plt
import random
import math

In [2]:
points = list()
x = [i for i in range(100)]
y = [(2*i)+1 for i in x]
for i in range(len(y)):
    ran = random.random()
    if i/2 == 0:
        x[i] = x[i] +(ran*2)
    else:
        y[i] = y[i] +(ran*2)

plt.plot(x,y,'o')
plt.show()

In [3]:
import numpy.linalg as la

# Sphere Fitting

### IMPORTANT: http://jekel.me/2015/Least-Squares-Sphere-Fit/
https://www.google.de/search?q=sphere+fitting+python&ie=utf-8&oe=utf-8&client=firefox-b&gfe_rd=cr&ei=inS_V6T2Mc2N8QemhIzYBQ

http://stackoverflow.com/questions/15785428/how-do-i-fit-3d-data

### Numerical Python: 
Chapter 5 (linear least square) and Chapter 6 (nonlinear least square).

# Least Squar
https://en.wikipedia.org/wiki/Least_squares#Relationship_to_principal_components
https://en.wikipedia.org/wiki/Non-linear_least_squares#Singular_value_decomposition

In [9]:
la.lstsq?

In [16]:
np.ones?

In [15]:
ones = np.ones((2,5))
print ones

s = (5,3)
ones = np.ones(s)
print ones

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [7]:
#Load Data
spX = np.loadtxt('xpoints.txt')
spY = np.loadtxt('ypoints.txt')
spZ = np.loadtxt('zpoints.txt')

In [10]:
spX = np.array(spX)
spY = np.array(spY)
spZ = np.array(spZ)
A = np.zeros((len(spX),4))
A[:,0] = spX*2
A[:,1] = spY*2
A[:,2] = spZ*2
A[:,3] = 1
#   Assemble the f matrix
f = np.zeros((len(spX),1))
f[:,0] = (spX*spX) + (spY*spY) + (spZ*spZ)
C, residules, rank, singval = np.linalg.lstsq(A,f)
#   solve for the radius
t= (C[0]*C[0])+(C[1]*C[1])+(C[2]*C[2])+C[3]
radius = math.sqrt(t)
print radius, C[0], C[1], C[2]

5.0 [ -1.71624642e-15] [ -1.78127499e-15] [ 5.]
